-- KyaUI: datos del perfil de ElvUI (extraido de Kyarox, perfil 'MerfinUI (DPS/Tank) (1080) v7.05'). Generado por tools/export-profiles.ps1. NO editar a mano.
local addonName, addonTable = ...
KyaUI = KyaUI or {}
KyaUI.ProfileData = {
			["databars"] = {
				["petExperience"] = {
					["textFormat"] = "CURMAX",
					["height"] = 20,
					["font"] = "SFUIDisplayCondensed-Semibold",
					["textSize"] = 14,
					["width"] = 300,
				},
				["experience"] = {
					["textFormat"] = "CURMAX",
					["width"] = 396,
					["font"] = "SFUIDisplayCondensed-Semibold",
					["showQuestXP"] = false,
					["fontOutline"] = "OUTLINE",
					["height"] = 27,
					["orientation"] = "HORIZONTAL",
					["textSize"] = 14,
					["showLevel"] = true,
				},
				["reputation"] = {
					["fontSize"] = 14,
				},
			},
			["currentTutorial"] = 1,
			["general"] = {
				["loginmessage"] = false,
				["fontSize"] = 13,
				["autoAcceptInvite"] = true,
				["afk"] = false,
				["autoRepair"] = "PLAYER",
				["minimap"] = {
					["clusterBackdrop"] = false,
					["locationFont"] = "SFUIDisplayCondensed-Semibold",
					["timeFont"] = "SFUIDisplayCondensed-Semibold",
					["timeFontSize"] = 12,
					["size"] = 199,
				},
				["font"] = "SFUIDisplayCondensed-Semibold",
				["bottomPanel"] = false,
				["backdropfadecolor"] = {
					["a"] = 0.80000001192093,
					["b"] = 0.058823529411765,
					["g"] = 0.058823529411765,
					["r"] = 0.058823529411765,
				},
				["valuecolor"] = {
					["b"] = 0,
					["g"] = 0.42352941176471,
					["r"] = 1,
				},
				["totems"] = {
					["fontSize"] = 14,
					["size"] = 28,
					["spacing"] = 1,
					["enable"] = false,
					["font"] = "SFUIDisplayCondensed-Semibold",
					["mouseover"] = false,
					["growthDirection"] = "HORIZONTAL",
				},
			},
			["enhanced"] = {
				["map"] = {
					["fogClear"] = {
						["enable"] = true,
					},
				},
				["general"] = {
					["showQuestLevel"] = true,
					["trainAllSkills"] = true,
					["hideZoneText"] = true,
					["altBuyMaxStack"] = true,
				},
				["blizzard"] = {
					["takeAllMail"] = true,
				},
				["tooltip"] = {
					["tooltipIcon"] = {
						["enable"] = true,
					},
					["itemQualityBorderColor"] = true,
				},
				["minimap"] = {
					["location"] = true,
					["buttonGrabber"] = {
						["buttonsPerRow"] = 10,
						["insideMinimap"] = {
							["xOffset"] = 0,
							["yOffset"] = 0,
							["position"] = "BOTTOMLEFT",
						},
						["buttonSpacing"] = -1,
					},
				},
				["equipment"] = {
					["enable"] = true,
					["fontSize"] = 12,
					["font"] = "SFUIDisplayCondensed-Semibold",
					["fontOutline"] = "OUTLINE",
				},
				["character"] = {
					["inspectBackground"] = true,
					["desaturateInspect"] = true,
					["petBackground"] = true,
					["characterBackground"] = true,
					["desaturateCharacter"] = true,
					["desaturateCompanion"] = true,
					["companionBackground"] = true,
					["animations"] = true,
				},
				["actionbar"] = {
					["keyPressAnimation"] = {
						["scale"] = 1,
					},
				},
				["loseControl"] = {
					["iconSize"] = 50,
					["Root"] = true,
					["compactMode"] = true,
					["Snare"] = true,
				},
				["chat"] = {
					["dpsLinks"] = true,
				},
			},
			["addOnSkins"] = {
				["dbmTemplate"] = "Transparent",
				["dbmFontOutline"] = "NONE",
				["dbmFont"] = "SFUIDisplayCondensed-Semibold",
				["skadaTitleTemplate"] = "Transparent",
				["dbmBarHeight"] = 27,
				["skadaTemplate"] = "Transparent",
				["omenTemplateGloss"] = true,
				["embed"] = {
					["rightWindow"] = "Omen",
					["leftWindowWidth"] = 190,
					["leftWindow"] = "Skada",
				},
				["skadaTemplateGloss"] = true,
			},
			["pz"] = {
				["nameplates"] = {
					["hdClient"] = {
						["hdNameplates"] = true,
					},
				},
				["unitframe"] = {
					["colors"] = {
						["absorbPrediction"] = {
							["absorbs"] = {
								["a"] = 0.35,
							},
							["overabsorbs"] = {
								["a"] = 0.35,
							},
						},
					},
					["units"] = {
						["pet"] = {
							["absorbPrediction"] = {
								["enable"] = false,
							},
						},
						["focus"] = {
							["absorbPrediction"] = {
								["enable"] = false,
							},
						},
						["player"] = {
							["absorbPrediction"] = {
								["enable"] = false,
								["absorbTexture"] = "Flatt",
								["overAbsorb"] = false,
							},
						},
						["raid40"] = {
							["absorbPrediction"] = {
								["overAbsorb"] = false,
							},
						},
						["raidpet"] = {
							["absorbPrediction"] = {
								["overAbsorb"] = false,
							},
						},
						["target"] = {
							["absorbPrediction"] = {
								["enable"] = false,
							},
						},
						["arena"] = {
							["absorbPrediction"] = {
								["enable"] = false,
							},
						},
						["raid"] = {
							["absorbPrediction"] = {
								["overAbsorb"] = false,
							},
						},
						["party"] = {
							["absorbPrediction"] = {
								["overAbsorb"] = false,
								["absorbTexture"] = "Flatt",
							},
						},
					},
				},
				["wratharmory"] = {
					["enable"] = false,
					["character"] = {
						["enchant"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
						},
					},
					["inspect"] = {
						["enchant"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
						},
					},
				},
			},
			["chat"] = {
				["panelBackdrop"] = "LEFT",
				["tabSelector"] = "ARROW3",
				["separateSizes"] = true,
				["showHistory"] = {
					["EMOTE"] = false,
					["CHANNEL"] = false,
					["INSTANCE"] = false,
				},
				["tabFont"] = "SFUIDisplayCondensed-Semibold",
				["panelColor"] = {
					["a"] = 0.67553424835205,
					["r"] = 0.058823529411765,
					["g"] = 0.058823529411765,
					["b"] = 0.058823529411765,
				},
				["tabFontSize"] = 13,
				["editBoxPosition"] = "ABOVE_CHAT_INSIDE",
				["panelHeightRight"] = 270,
				["panelColorConverted"] = true,
				["panelTabTransparency"] = true,
				["panelHeight"] = 250,
				["font"] = "SFUIDisplayCondensed-Semibold",
				["panelWidthRight"] = 230,
				["timeStampFormat"] = "%H:%M:%S",
				["panelWidth"] = 396,
			},
			["movers"] = {
				["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-62",
				["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,220",
				["RaidMarkerBarAnchor"] = "TOP,UIParent,TOP,0,-4",
				["MinimapButtonAnchor"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,-203",
				["ElvUF_RaidMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,281",
				["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,29",
				["GMMover"] = "TOPLEFT,UIParent,TOPLEFT,284,-4",
				["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-209,-4",
				["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,-200,514",
				["AlertFrameMover"] = "TOP,ElvUIParent,TOP,288,-322",
				["BagsMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-763,4",
				["DTPanelCustomPanel_LeftMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,4",
				["LootFrameMover"] = "TOP,UIParent,TOP,0,-218",
				["ZoneAbility"] = "TOP,ElvUIParent,TOP,200,-514",
				["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,29",
				["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-403",
				["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,29",
				["DTB2_DBT2_RightBottomBar_Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,4",
				["TotemBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,499",
				["ArenaHeaderMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-387,-344",
				["ElvUF_FocusMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-256,280",
				["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,267,280",
				["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,285,284",
				["ClassBarMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,4,491",
				["DurabilityFrameMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-7,430",
				["ElvUF_PetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,222",
				["VehicleSeatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,404,4",
				["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-447,280",
				["ExperienceBarMover"] = "TOP,UIParent,TOP,0,-4",
				["ElvTooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,409",
				["ElvUIBankMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,280",
				["ElvBar_Pet"] = "BOTTOM,ElvUIParent,BOTTOM,0,66",
				["LossControlMover"] = "TOP,UIParent,TOP,0,-490",
				["ElvUF_Raid40Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,281",
				["ElvBar_Totem"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-5,424",
				["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,289,-81",
				["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,-186,4",
				["ElvAB_2"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,316",
				["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-246,-209",
				["BNETMover"] = "TOPLEFT,UIParent,TOPLEFT,496,-4",
				["DTPanelCustomPanel_RightMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,4",
				["DTB2_DBT2_LeftBottomBar_Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,4",
				["PetExperienceBarMover"] = "TOP,ElvUIParent,TOP,0,-30",
				["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,186,4",
				["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,186,35",
				["VehicleLeaveButton"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,404,134",
				["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,-186,35",
				["WatchFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-211",
				["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-34,-246",
				["TotemTrackerMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,404,4",
				["ShiftAB"] = "BOTTOM,ElvUIParent,BOTTOM,-179,70",
				["SquareMinimapButtonBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-208",
				["HonorBarMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,528,-338",
				["ElvAB_6"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,424,551",
				["MicrobarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-240,4",
				["ElvUF_TankMover"] = "BOTTOM,ElvUIParent,BOTTOM,-303,49",
				["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-387,-370",
				["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,447,280",
				["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-267,280",
				["ElvUF_PartyMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,418,-361",
				["TimeManagerFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-412",
				["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-209,-154",
				["MinimapMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-4",
			},
			["tooltip"] = {
				["headerFont"] = "SFUIDisplayCondensed-Semibold",
				["font"] = "SFUIDisplayCondensed-Semibold",
				["healthBar"] = {
					["height"] = 2,
					["fontSize"] = 12,
					["font"] = "SFUIDisplayCondensed-Semibold",
					["text"] = false,
				},
				["fontOutline"] = "OUTLINE",
				["visibility"] = {
					["combatOverride"] = "SHIFT",
				},
				["headerFontOutline"] = "OUTLINE",
			},
			["enhanceFriendsList"] = {
				["showStatusIcon"] = false,
				["nameFont"] = "SFUIDisplayCondensed-Semibold",
				["Offline"] = {
					["classIcon"] = true,
					["enhancedName"] = true,
				},
				["zoneFont"] = "SFUIDisplayCondensed-Semibold",
				["Online"] = {
					["colorizeNameOnly"] = true,
					["enhancedZone"] = true,
					["shortLevel"] = true,
					["classIcon"] = true,
					["sameZone"] = true,
					["enhancedName"] = true,
				},
			},
			["hideTutorial"] = 1,
			["nameplates"] = {
				["threat"] = {
					["badScale"] = 1,
					["goodScale"] = 1,
				},
				["nonTargetTransparency"] = 1,
				["alwaysShowTargetHealth"] = false,
				["units"] = {
					["FRIENDLY_PLAYER"] = {
						["debuffs"] = {
							["countFontSize"] = 10,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["durationFontSize"] = 10,
							["durationFont"] = "SFUIDisplayCondensed-Semibold",
							["countYOffset"] = 0,
							["yOffset"] = 4,
							["attachTo"] = "FRAME",
							["countXOffset"] = 0,
							["spacing"] = 0,
							["size"] = 20,
							["xOffset"] = 1,
							["perrow"] = 7,
							["filters"] = {
								["priority"] = "Blacklist,CCDebuffs,Personal",
							},
						},
						["health"] = {
							["height"] = 18,
							["text"] = {
								["fontSize"] = 9,
								["enable"] = true,
								["position"] = "BOTTOMRIGHT",
								["xOffset"] = -2,
								["format"] = "CURRENT_PERCENT",
								["font"] = "SFUIDisplayCondensed-Semibold",
								["yOffset"] = 14,
							},
							["width"] = 145,
						},
						["castbar"] = {
							["width"] = 145,
							["fontSize"] = 9,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["iconOffsetX"] = 0,
							["height"] = 15,
							["textPosition"] = "ONBAR",
							["iconSize"] = 34,
							["yOffset"] = -1,
						},
						["buffs"] = {
							["durationFont"] = "SFUIDisplayCondensed-Semibold",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["enable"] = false,
						},
						["level"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
						},
						["raidTargetIndicator"] = {
							["xOffset"] = -6,
							["size"] = 23,
						},
						["name"] = {
							["abbrev"] = true,
							["fontSize"] = 9,
							["position"] = "BOTTOMLEFT",
							["xOffset"] = 2,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 14,
						},
					},
					["TARGET"] = {
						["glowStyle"] = "style1",
						["comboPoints"] = {
							["enable"] = false,
						},
						["arrow"] = "Arrow1",
					},
					["FRIENDLY_NPC"] = {
						["debuffs"] = {
							["countFontSize"] = 10,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["durationFontSize"] = 10,
							["durationFont"] = "SFUIDisplayCondensed-Semibold",
							["countYOffset"] = 0,
							["yOffset"] = 4,
							["attachTo"] = "FRAME",
							["countXOffset"] = 0,
							["spacing"] = 0,
							["size"] = 20,
							["xOffset"] = 1,
							["perrow"] = 7,
							["filters"] = {
								["priority"] = "Blacklist,CCDebuffs,Personal",
							},
						},
						["name"] = {
							["abbrev"] = true,
							["fontSize"] = 9,
							["position"] = "BOTTOMLEFT",
							["xOffset"] = 2,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 14,
						},
						["castbar"] = {
							["width"] = 145,
							["fontSize"] = 9,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["iconOffsetX"] = 0,
							["height"] = 15,
							["textPosition"] = "ONBAR",
							["iconSize"] = 34,
							["yOffset"] = -1,
						},
						["health"] = {
							["height"] = 18,
							["text"] = {
								["fontSize"] = 9,
								["enable"] = true,
								["position"] = "BOTTOMRIGHT",
								["xOffset"] = -2,
								["format"] = "CURRENT_PERCENT",
								["font"] = "SFUIDisplayCondensed-Semibold",
								["yOffset"] = 14,
							},
							["width"] = 145,
						},
						["level"] = {
							["enable"] = false,
							["font"] = "SFUIDisplayCondensed-Semibold",
						},
						["raidTargetIndicator"] = {
							["xOffset"] = -6,
							["size"] = 23,
						},
						["buffs"] = {
							["durationFont"] = "SFUIDisplayCondensed-Semibold",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["enable"] = false,
						},
					},
					["ENEMY_PLAYER"] = {
						["debuffs"] = {
							["countFontSize"] = 10,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["durationFontSize"] = 10,
							["durationFont"] = "SFUIDisplayCondensed-Semibold",
							["countYOffset"] = 0,
							["yOffset"] = 4,
							["attachTo"] = "FRAME",
							["countXOffset"] = 0,
							["spacing"] = 0,
							["size"] = 20,
							["xOffset"] = 1,
							["perrow"] = 7,
							["filters"] = {
								["priority"] = "Blacklist,CCDebuffs,Personal",
							},
						},
						["name"] = {
							["abbrev"] = true,
							["fontSize"] = 9,
							["position"] = "BOTTOMLEFT",
							["xOffset"] = 2,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 14,
						},
						["castbar"] = {
							["width"] = 145,
							["fontSize"] = 9,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["iconOffsetX"] = 0,
							["height"] = 15,
							["textPosition"] = "ONBAR",
							["iconSize"] = 34,
							["yOffset"] = -1,
						},
						["buffs"] = {
							["durationFont"] = "SFUIDisplayCondensed-Semibold",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["enable"] = false,
							["filters"] = {
								["priority"] = "Blacklist,blockNoDuration,Personal,TurtleBuffs",
							},
						},
						["level"] = {
							["enable"] = false,
							["font"] = "SFUIDisplayCondensed-Semibold",
						},
						["raidTargetIndicator"] = {
							["xOffset"] = -6,
							["size"] = 23,
						},
						["health"] = {
							["height"] = 18,
							["text"] = {
								["fontSize"] = 9,
								["enable"] = true,
								["position"] = "BOTTOMRIGHT",
								["xOffset"] = -2,
								["format"] = "CURRENT_PERCENT",
								["font"] = "SFUIDisplayCondensed-Semibold",
								["yOffset"] = 14,
							},
							["width"] = 145,
						},
					},
					["ENEMY_NPC"] = {
						["debuffs"] = {
							["countFontSize"] = 10,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["durationFontSize"] = 10,
							["durationFont"] = "SFUIDisplayCondensed-Semibold",
							["countYOffset"] = 0,
							["yOffset"] = 4,
							["attachTo"] = "FRAME",
							["countXOffset"] = 0,
							["spacing"] = 0,
							["size"] = 20,
							["xOffset"] = 1,
							["perrow"] = 7,
							["filters"] = {
								["priority"] = "Blacklist,CCDebuffs,Personal",
							},
						},
						["name"] = {
							["abbrev"] = true,
							["fontSize"] = 9,
							["position"] = "BOTTOMLEFT",
							["xOffset"] = 2,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 14,
						},
						["castbar"] = {
							["width"] = 145,
							["fontSize"] = 9,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["iconOffsetX"] = 0,
							["height"] = 15,
							["textPosition"] = "ONBAR",
							["iconSize"] = 34,
							["yOffset"] = -1,
						},
						["health"] = {
							["height"] = 18,
							["text"] = {
								["fontSize"] = 9,
								["enable"] = true,
								["position"] = "BOTTOMRIGHT",
								["xOffset"] = -2,
								["format"] = "CURRENT_PERCENT",
								["font"] = "SFUIDisplayCondensed-Semibold",
								["yOffset"] = 14,
							},
							["width"] = 145,
						},
						["level"] = {
							["enable"] = false,
							["font"] = "SFUIDisplayCondensed-Semibold",
						},
						["raidTargetIndicator"] = {
							["xOffset"] = -6,
							["size"] = 23,
						},
						["buffs"] = {
							["durationFont"] = "SFUIDisplayCondensed-Semibold",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["enable"] = false,
							["filters"] = {
								["priority"] = "Blacklist,blockNoDuration,Personal,TurtleBuffs",
							},
						},
					},
				},
				["statusbar"] = "Flatt",
				["useTargetScale"] = false,
				["clickThrough"] = {
					["friendly"] = true,
				},
				["plateSize"] = {
					["enemyHeight"] = 16,
					["enemyWidth"] = 130,
					["friendlyWidth"] = 130,
					["friendlyHeight"] = 16,
				},
				["targetScale"] = 1.1,
				["fadeIn"] = false,
				["filters"] = {
					["Mark_Circle"] = {
						["triggers"] = {
							["enable"] = true,
						},
					},
					["Mark_Cross"] = {
						["triggers"] = {
							["enable"] = true,
						},
					},
					["Mark_Moon"] = {
						["triggers"] = {
							["enable"] = true,
						},
					},
					["Mark_Star"] = {
						["triggers"] = {
							["enable"] = true,
						},
					},
					["Mark_Triangle"] = {
						["triggers"] = {
							["enable"] = true,
						},
					},
					["Mark_Skull"] = {
						["triggers"] = {
							["enable"] = true,
						},
					},
					["Mark_Diamond"] = {
						["triggers"] = {
							["enable"] = true,
						},
					},
					["Mark_Square"] = {
						["triggers"] = {
							["enable"] = true,
						},
					},
				},
			},
			["CustomTweaks"] = {
				["CastbarFont"] = {
					["Player"] = {
						["text"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 15,
							["fontOutline"] = "OUTLINE",
						},
						["duration"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 15,
							["fontOutline"] = "OUTLINE",
						},
					},
					["Focus"] = {
						["text"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "OUTLINE",
						},
						["duration"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "OUTLINE",
						},
					},
					["Target"] = {
						["text"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "OUTLINE",
						},
						["duration"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "OUTLINE",
						},
					},
					["Arena"] = {
						["text"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "NONE",
						},
						["duration"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "NONE",
						},
					},
					["Pet"] = {
						["text"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "NONE",
						},
						["duration"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "NONE",
						},
					},
					["Boss"] = {
						["text"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "NONE",
						},
						["duration"] = {
							["font"] = "SFUIDisplayCondensed-Semibold",
							["fontSize"] = 13,
							["fontOutline"] = "NONE",
						},
					},
				},
				["CastbarText"] = {
					["Player"] = {
						["text"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
						["duration"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
					},
					["Focus"] = {
						["text"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
						["duration"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
					},
					["Target"] = {
						["text"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
						["duration"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
					},
					["Arena"] = {
						["text"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
						["duration"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
					},
					["Pet"] = {
						["text"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
						["duration"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
					},
					["Boss"] = {
						["text"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
						["duration"] = {
							["color"] = {
								["b"] = 1,
								["g"] = 1,
								["r"] = 1,
							},
						},
					},
				},
				["RaidControl"] = {
					["hide"] = true,
				},
				["AuraIconSpacing"] = {
					["units"] = {
						["raid"] = false,
						["party"] = false,
						["raid40"] = false,
						["raidpet"] = false,
					},
					["spacing"] = -1,
				},
				["BagButtons"] = {
					["stackButton"] = true,
				},
			},
			["datatexts"] = {
				["minimapPanels"] = false,
				["font"] = "SFUIDisplayCondensed-Semibold",
				["leftChatPanel"] = false,
				["panels"] = {
					["DTB2_DBT2_LeftBottomBar"] = {
						["left"] = "System",
						["right"] = "Time",
					},
					["DTB2_DBT2_RightBottomBar"] = {
						["left"] = "Durability",
						["right"] = "Gold",
					},
				},
				["rightChatPanel"] = false,
			},
			["actionbar"] = {
				["bar3"] = {
					["visibility"] = "",
					["backdropSpacing"] = 0,
					["buttons"] = 12,
					["showGrid"] = false,
					["buttonsPerRow"] = 12,
					["alpha"] = 0.85,
					["buttonspacing"] = -1,
				},
				["fontSize"] = 14,
				["hotkeyTextPosition"] = "TOPLEFT",
				["desaturateOnCooldown"] = true,
				["fontOutline"] = "OUTLINE",
				["countTextPosition"] = "BOTTOMLEFT",
				["microbar"] = {
					["enabled"] = true,
					["buttonSize"] = 15,
					["backdropSpacing"] = 0,
					["transparentBackdrop"] = true,
					["alpha"] = 0.7,
					["buttonSpacing"] = 1,
				},
				["transparentBackdrops"] = true,
				["bar4"] = {
					["visibility"] = "",
					["backdropSpacing"] = 0,
					["showGrid"] = false,
					["buttonspacing"] = -1,
					["buttonsPerRow"] = 12,
					["alpha"] = 0.85,
					["backdrop"] = false,
				},
				["cooldown"] = {
					["fonts"] = {
						["enable"] = true,
						["font"] = "SFUIDisplayCondensed-Semibold",
						["fontSize"] = 14,
					},
					["hhmmColor"] = {
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["mmssColor"] = {
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["mmssThreshold"] = 300,
					["threshold"] = -1,
					["checkSeconds"] = true,
				},
				["bar6"] = {
					["visibility"] = "",
					["showGrid"] = false,
					["backdropSpacing"] = 0,
					["alpha"] = 0.85,
					["buttonspacing"] = -1,
				},
				["bar2"] = {
					["visibility"] = "",
					["showGrid"] = false,
					["backdropSpacing"] = 0,
					["alpha"] = 0.85,
					["buttonspacing"] = -1,
				},
				["bar1"] = {
					["buttonspacing"] = -1,
					["alpha"] = 0.85,
					["backdropSpacing"] = 0,
					["showGrid"] = false,
				},
				["macrotext"] = true,
				["transparentButtons"] = true,
				["bar5"] = {
					["visibility"] = "",
					["backdropSpacing"] = 0,
					["buttons"] = 12,
					["showGrid"] = false,
					["buttonsPerRow"] = 12,
					["alpha"] = 0.85,
					["buttonspacing"] = -1,
				},
				["countTextYOffset"] = 1,
				["font"] = "SFUIDisplayCondensed-Semibold",
				["barTotem"] = {
					["buttonspacing"] = 1,
					["alpha"] = 0.6,
					["mouseover"] = true,
				},
				["hotkeyTextXOffset"] = 1,
				["hotkeyTextYOffset"] = -1,
				["stanceBar"] = {
					["point"] = "BOTTOMLEFT",
					["buttons"] = 9,
					["buttonsPerRow"] = 9,
					["alpha"] = 0.7,
					["style"] = "classic",
				},
				["barPet"] = {
					["enabled"] = false,
					["backdropSpacing"] = 0,
					["point"] = "TOPLEFT",
					["backdrop"] = false,
					["showGrid"] = false,
					["buttonsPerRow"] = 10,
					["alpha"] = 0.8,
					["buttonspacing"] = -1,
				},
				["countTextXOffset"] = 1,
			},
			["dtbars"] = {
				["DTB2_DBT2_LeftBottomBar"] = {
					["enable"] = true,
					["growth"] = "HORIZONTAL",
					["width"] = 396,
					["combatHide"] = false,
					["transparent"] = true,
					["height"] = 22,
					["border"] = true,
					["vehicleHide"] = false,
					["mouseover"] = false,
				},
				["DTB2_DBT2_RightBottomBar"] = {
					["enable"] = true,
					["growth"] = "HORIZONTAL",
					["width"] = 232,
					["combatHide"] = false,
					["transparent"] = true,
					["height"] = 22,
					["border"] = true,
					["vehicleHide"] = false,
					["mouseover"] = false,
				},
			},
			["unitframe"] = {
				["statusbar"] = "Flatt",
				["fontSize"] = 14,
				["colors"] = {
					["debuffHighlight"] = {
						["blendMode"] = "ALPHAKEY",
					},
					["power"] = {
						["MANA"] = {
							["b"] = 1,
							["g"] = 0.86274509803922,
							["r"] = 0.019607843137255,
						},
					},
					["castColor"] = {
						["b"] = 0,
						["g"] = 0.67843137254902,
						["r"] = 1,
					},
					["castbar_backdrop"] = {
						["b"] = 0.10588235294118,
						["g"] = 0.10588235294118,
						["r"] = 0.2078431372549,
					},
					["colorhealthbyvalue"] = false,
					["healthclass"] = true,
					["customhealthbackdrop"] = true,
					["health_backdrop"] = {
						["b"] = 0.23137254901961,
						["g"] = 0.23137254901961,
						["r"] = 0.27058823529412,
					},
					["customcastbarbackdrop"] = true,
					["health"] = {
						["b"] = 0.17254901960784,
						["g"] = 0.17254901960784,
						["r"] = 0.1921568627451,
					},
					["castNoInterrupt"] = {
						["b"] = 0.25098039215686,
						["g"] = 0.25098039215686,
						["r"] = 0.78039215686275,
					},
					["frameGlow"] = {
						["targetGlow"] = {
							["enable"] = false,
						},
						["mouseoverGlow"] = {
							["enable"] = false,
						},
					},
					["transparentHealth"] = true,
					["health_backdrop_dead"] = {
						["b"] = 0.46274509803922,
						["g"] = 0.46274509803922,
						["r"] = 0.51764705882353,
					},
				},
				["smartRaidFilter"] = false,
				["font"] = "SFUIDisplayCondensed-Semibold",
				["fontOutline"] = "OUTLINE",
				["cooldown"] = {
					["fonts"] = {
						["enable"] = true,
						["font"] = "SFUIDisplayCondensed-Semibold",
						["fontSize"] = 20,
					},
				},
				["units"] = {
					["boss"] = {
						["debuffs"] = {
							["countFontSize"] = 13,
							["sizeOverride"] = 30,
							["perrow"] = 6,
							["xOffset"] = -3,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["numrows"] = 1,
							["yOffset"] = 0,
						},
						["power"] = {
							["text_format"] = "",
							["height"] = 6,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 2,
								["text_format"] = "[name:veryshort]",
								["yOffset"] = 8,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitPower"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = -2,
								["text_format"] = "[power:current]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "RIGHT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitHealth"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 2,
								["text_format"] = "[health:percent]",
								["yOffset"] = -8,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
						},
						["colorOverride"] = "FORCE_ON",
						["growthDirection"] = "UP",
						["health"] = {
							["frequentUpdates"] = true,
							["text_format"] = "",
						},
						["castbar"] = {
							["enable"] = false,
						},
						["height"] = 44,
						["buffs"] = {
							["countFontSize"] = 11,
							["sizeOverride"] = 20,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["xOffset"] = 3,
							["numrows"] = 2,
							["anchorPoint"] = "RIGHT",
							["yOffset"] = 10,
						},
						["name"] = {
							["text_format"] = "",
						},
						["width"] = 180,
					},
					["tank"] = {
						["debuffs"] = {
							["countFontSize"] = 13,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
						},
						["threatStyle"] = "NONE",
						["enable"] = false,
						["rdebuffs"] = {
							["enable"] = false,
							["font"] = "SFUIDisplayCondensed-Semibold",
						},
						["colorOverride"] = "FORCE_ON",
						["width"] = 100,
						["name"] = {
							["text_format"] = "[name:medium]",
						},
						["height"] = 45,
						["verticalSpacing"] = 1,
						["targetsGroup"] = {
							["enable"] = false,
						},
					},
					["targettargettarget"] = {
						["colorOverride"] = "FORCE_ON",
						["health"] = {
							["frequentUpdates"] = true,
						},
					},
					["party"] = {
						["horizontalSpacing"] = -1,
						["debuffs"] = {
							["numrows"] = 2,
							["sizeOverride"] = 25,
							["perrow"] = 3,
							["xOffset"] = 2,
							["priority"] = "Blacklist,RaidDebuffs_VoA,RaidDebuffs_OS,RaidDebuffs_Naxx,RaidDebuffs_EoE,RaidDebuffs_Ulduar,RaidDebuffs_ToGC,RaidDebuffs_ICC,RaidDebuffs_RS,Dispellable",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 13,
						},
						["rdebuffs"] = {
							["fontSize"] = 12,
							["fontOutline"] = "OUTLINE",
							["size"] = 30,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 10,
						},
						["colorOverride"] = "FORCE_ON",
						["groupBy"] = "ROLE",
						["threatStyle"] = "ICONLEFT",
						["power"] = {
							["height"] = 6,
							["text_format"] = "",
							["enable"] = false,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[name:veryshort]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["OfflineStatus"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[namecolor][offline]",
								["yOffset"] = 14,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = false,
								["size"] = 12,
							},
							["UnitHealth"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = -5,
								["text_format"] = "[health:percent]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "RIGHT",
								["fontOutline"] = "OUTLINE",
								["enable"] = false,
								["size"] = 14,
							},
							["DeadGhostStatus"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[namecolor][dead]",
								["yOffset"] = 14,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 12,
							},
						},
						["healPrediction"] = {
							["overAbsorb"] = false,
							["absorbTexture"] = "Flatt",
						},
						["buffIndicator"] = {
							["countFontSize"] = 14,
						},
						["width"] = 230,
						["sortDir"] = "DESC",
						["health"] = {
							["text_format"] = "",
						},
						["name"] = {
							["text_format"] = "",
						},
						["verticalSpacing"] = -1,
						["height"] = 55,
						["buffs"] = {
							["anchorPoint"] = "RIGHT",
							["sizeOverride"] = 22,
							["xOffset"] = -115,
							["spacing"] = -1,
							["enable"] = true,
							["priority"] = "Defensivos",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["perrow"] = 3,
						},
						["petsGroup"] = {
							["anchorPoint"] = "LEFT",
							["name"] = {
								["text_format"] = "[health:percent]",
							},
							["enable"] = true,
							["xOffset"] = -131,
							["height"] = 35,
							["width"] = 90,
						},
						["readycheckIcon"] = {
							["attachTo"] = "CENTER",
							["yOffset"] = 13,
							["size"] = 20,
						},
					},
					["raid"] = {
						["horizontalSpacing"] = -1,
						["debuffs"] = {
							["anchorPoint"] = "TOPLEFT",
							["sizeOverride"] = 16,
							["enable"] = true,
							["priority"] = "Blacklist,BLACKLIST: Debuff Indicators,RaidDebuffs_VoA,RaidDebuffs_OS,RaidDebuffs_Naxx,RaidDebuffs_EoE,RaidDebuffs_Ulduar,RaidDebuffs_ToGC,RaidDebuffs_ICC,RaidDebuffs_RS,Dispellable",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = -16,
						},
						["rdebuffs"] = {
							["fontOutline"] = "OUTLINE",
							["fontSize"] = 12,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 7,
						},
						["colorOverride"] = "FORCE_ON",
						["growthDirection"] = "RIGHT_UP",
						["buffIndicator"] = {
							["countFontSize"] = 14,
						},
						["roleIcon"] = {
							["healer"] = false,
							["damager"] = false,
						},
						["threatStyle"] = "ICONLEFT",
						["power"] = {
							["enable"] = false,
							["position"] = "RIGHT",
							["height"] = 4,
							["yOffset"] = 0,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[name:veryshort]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["DeadGhostStatus"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[namecolor][dead]",
								["yOffset"] = 15,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 12,
							},
						},
						["healPrediction"] = {
							["overAbsorb"] = false,
						},
						["groupBy"] = "ROLE",
						["raidRoleIcons"] = {
							["enable"] = false,
							["yOffset"] = 3,
						},
						["health"] = {
							["text_format"] = "",
						},
						["verticalSpacing"] = -1,
						["orientation"] = "LEFT",
						["buffs"] = {
							["anchorPoint"] = "RIGHT",
							["sizeOverride"] = 22,
							["enable"] = true,
							["priority"] = "Defensivos",
							["xOffset"] = -60,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
						},
						["name"] = {
							["text_format"] = "",
						},
						["readycheckIcon"] = {
							["attachTo"] = "CENTER",
							["yOffset"] = 13,
							["size"] = 20,
						},
					},
					["focustarget"] = {
						["colorOverride"] = "FORCE_ON",
						["health"] = {
							["frequentUpdates"] = true,
						},
					},
					["targettarget"] = {
						["debuffs"] = {
							["countFontSize"] = 13,
							["sizeOverride"] = 37,
							["enable"] = false,
							["yOffset"] = -2,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[name:abbrev:medium]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
						},
						["colorOverride"] = "FORCE_ON",
						["width"] = 120,
						["fader"] = {
							["enable"] = false,
						},
						["name"] = {
							["text_format"] = "",
						},
						["orientation"] = "RIGHT",
						["buffs"] = {
							["countFontSize"] = 13,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["maxDuration"] = 0,
							["anchorPoint"] = "TOPRIGHT",
							["yOffset"] = -2,
						},
						["height"] = 44,
						["health"] = {
							["frequentUpdates"] = true,
						},
					},
					["assist"] = {
						["enable"] = false,
						["colorOverride"] = "FORCE_ON",
					},
					["raidpet"] = {
						["horizontalSpacing"] = -1,
						["debuffs"] = {
							["countFontSize"] = 11,
							["sizeOverride"] = 17,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["enable"] = true,
							["priority"] = "Blacklist,RaidDebuffs_VoA,RaidDebuffs_OS,RaidDebuffs_Naxx,RaidDebuffs_EoE,RaidDebuffs_Ulduar,RaidDebuffs_ToGC,RaidDebuffs_ICC,RaidDebuffs_RS,Dispellable",
							["anchorPoint"] = "TOPLEFT",
							["yOffset"] = -17,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[name:veryshort]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
						},
						["rdebuffs"] = {
							["enable"] = false,
							["fontSize"] = 12,
						},
						["colorOverride"] = "FORCE_ON",
						["width"] = 47,
						["name"] = {
							["text_format"] = "",
						},
						["health"] = {
							["text_format"] = "",
						},
						["orientation"] = "LEFT",
						["height"] = 35,
						["verticalSpacing"] = -1,
						["healPrediction"] = {
							["overAbsorb"] = false,
						},
						["numGroups"] = 3,
					},
					["player"] = {
						["debuffs"] = {
							["anchorPoint"] = "TOPRIGHT",
							["enable"] = false,
						},
						["raidRoleIcons"] = {
							["enable"] = false,
						},
						["CombatIcon"] = {
							["size"] = 23,
						},
						["aurabar"] = {
							["enable"] = false,
						},
						["roleIcon"] = {
						},
						["threatStyle"] = "NONE",
						["power"] = {
							["detachFromFrame"] = true,
							["powerPrediction"] = true,
							["enable"] = false,
							["EnergyManaRegen"] = true,
							["text_format"] = "",
							["height"] = 8,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 5,
								["text_format"] = "[name]",
								["yOffset"] = 20,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = false,
								["size"] = 13,
							},
							["AltPowerValue"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 3,
								["text_format"] = "[altpowercolor][classpower:current]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = false,
								["size"] = 13,
							},
							["UnitPower"] = {
								["attachTextTo"] = "Power",
								["xOffset"] = 0,
								["text_format"] = "[power:current]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = false,
								["size"] = 13,
							},
							["UnitHealth"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = -2,
								["text_format"] = "[health:current]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "RIGHT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
						},
						["healPrediction"] = {
							["enable"] = false,
							["absorbTexture"] = "Flatt",
							["overAbsorb"] = false,
						},
						["raidicon"] = {
							["attachTo"] = "LEFT",
							["xOffset"] = 5,
							["yOffset"] = 0,
							["attachToObject"] = "Health",
							["size"] = 23,
						},
						["width"] = 235,
						["classbar"] = {
							["enable"] = false,
						},
						["RestIcon"] = {
							["enable"] = false,
						},
						["health"] = {
							["frequentUpdates"] = true,
							["text_format"] = "",
						},
						["castbar"] = {
							["spark"] = false,
							["enable"] = false,
							["format"] = "CURRENTMAX",
							["height"] = 33,
							["width"] = 275,
						},
						["height"] = 44,
						["buffs"] = {
							["anchorPoint"] = "TOPRIGHT",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
						},
						["colorOverride"] = "FORCE_ON",
						["pvp"] = {
							["text_format"] = "",
						},
					},
					["raid40"] = {
						["horizontalSpacing"] = -1,
						["debuffs"] = {
							["anchorPoint"] = "TOPLEFT",
							["sizeOverride"] = 16,
							["enable"] = true,
							["priority"] = "Blacklist,BLACKLIST: Debuff Indicators,RaidDebuffs_VoA,RaidDebuffs_OS,RaidDebuffs_Naxx,RaidDebuffs_EoE,RaidDebuffs_Ulduar,RaidDebuffs_ToGC,RaidDebuffs_ICC,RaidDebuffs_RS,Dispellable",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = -16,
						},
						["rdebuffs"] = {
							["fontSize"] = 12,
							["fontOutline"] = "OUTLINE",
							["enable"] = true,
							["size"] = 26,
							["font"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 7,
						},
						["colorOverride"] = "FORCE_ON",
						["growthDirection"] = "RIGHT_UP",
						["buffIndicator"] = {
							["countFontSize"] = 14,
						},
						["roleIcon"] = {
						},
						["threatStyle"] = "ICONLEFT",
						["power"] = {
							["height"] = 4,
							["position"] = "RIGHT",
							["yOffset"] = 0,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[name:veryshort]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["DeadGhostStatus"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[namecolor][dead]",
								["yOffset"] = 15,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 12,
							},
						},
						["healPrediction"] = {
							["overAbsorb"] = false,
						},
						["raidRoleIcons"] = {
							["enable"] = false,
							["yOffset"] = 3,
						},
						["groupBy"] = "ROLE",
						["verticalSpacing"] = -1,
						["orientation"] = "LEFT",
						["health"] = {
							["text_format"] = "",
							["yOffset"] = 0,
						},
						["numGroups"] = 5,
						["height"] = 44,
						["buffs"] = {
							["anchorPoint"] = "BOTTOMLEFT",
							["sizeOverride"] = 16,
							["enable"] = true,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 16,
						},
						["name"] = {
							["text_format"] = "",
						},
						["readycheckIcon"] = {
							["attachTo"] = "CENTER",
							["yOffset"] = 13,
							["size"] = 20,
						},
					},
					["focus"] = {
						["roleIcon"] = {
						},
						["debuffs"] = {
							["countFontSize"] = 13,
							["sizeOverride"] = 37,
							["enable"] = false,
							["yOffset"] = -2,
							["anchorPoint"] = "LEFT",
							["spacing"] = -1,
							["xOffset"] = -7,
							["priority"] = "Blacklist,Personal,RaidDebuffs,CCDebuffs,Friendly:Dispellable",
							["perrow"] = 6,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
						},
						["disableTargetGlow"] = true,
						["castbar"] = {
							["spark"] = false,
							["enable"] = false,
							["height"] = 27,
							["strataAndLevel"] = {
								["frameStrata"] = "BACKGROUND",
								["useCustomStrata"] = true,
							},
							["width"] = 180,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 2,
								["text_format"] = "[name:medium]",
								["yOffset"] = 8,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitPower"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = -3,
								["text_format"] = "[power:current]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "RIGHT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitHealth"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 2,
								["text_format"] = "[health:percent] || [health:current]",
								["yOffset"] = -8,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
						},
						["healPrediction"] = {
							["enable"] = false,
						},
						["colorOverride"] = "FORCE_ON",
						["width"] = 180,
						["name"] = {
							["text_format"] = "",
						},
						["health"] = {
							["frequentUpdates"] = true,
						},
						["fader"] = {
							["enable"] = false,
						},
						["height"] = 44,
						["orientation"] = "RIGHT",
						["buffs"] = {
							["countFontSize"] = 13,
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["spacing"] = -1,
							["growthX"] = "LEFT",
							["maxDuration"] = 0,
							["priority"] = "Blacklist,Personal,nonPersonal",
							["anchorPoint"] = "TOPRIGHT",
							["yOffset"] = -2,
						},
						["power"] = {
							["attachTextTo"] = "Power",
							["height"] = 6,
							["position"] = "CENTER",
						},
						["threatStyle"] = "NONE",
					},
					["target"] = {
						["combobar"] = {
							["enable"] = false,
						},
						["debuffs"] = {
							["countFontSize"] = 13,
							["sizeOverride"] = 23,
							["spacing"] = -1,
							["attachTo"] = "FRAME",
							["priority"] = "Blacklist,Friendly:Personal,Friendly:RaidDebuffs,Friendly:CCDebuffs,Friendly:Dispellable,Friendly:notCastByUnit,Friendly:CastByNPC",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = -1,
						},
						["colorOverride"] = "FORCE_ON",
						["aurabar"] = {
							["enable"] = false,
						},
						["roleIcon"] = {
						},
						["threatStyle"] = "NONE",
						["power"] = {
							["text_format"] = "",
							["height"] = 6,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 2,
								["text_format"] = "[namecolor][name:medium]",
								["yOffset"] = 8,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitPower"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = -2,
								["text_format"] = "[power:current]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "RIGHT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitHealth"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 2,
								["text_format"] = "[health:percent] || [health:current]",
								["yOffset"] = -8,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
						},
						["healPrediction"] = {
							["enable"] = false,
						},
						["width"] = 235,
						["castbar"] = {
							["spark"] = false,
							["enable"] = false,
							["height"] = 27,
							["strataAndLevel"] = {
								["useCustomLevel"] = true,
							},
							["width"] = 235,
						},
						["name"] = {
							["text_format"] = "",
						},
						["health"] = {
							["frequentUpdates"] = true,
							["text_format"] = "",
						},
						["fader"] = {
							["enable"] = false,
							["range"] = false,
						},
						["height"] = 44,
						["buffs"] = {
							["countFontSize"] = 13,
							["sizeOverride"] = 23,
							["spacing"] = -1,
							["attachTo"] = "DEBUFFS",
							["priority"] = "Blacklist,Personal,Friendly:nonPersonal",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = -1,
						},
						["smartAuraPosition"] = "FLUID_BUFFS_ON_DEBUFFS",
						["raidicon"] = {
							["attachTo"] = "CENTER",
							["yOffset"] = 0,
							["attachToObject"] = "Health",
							["size"] = 23,
						},
					},
					["arena"] = {
						["roleIcon"] = {
						},
						["debuffs"] = {
							["countFontSize"] = 13,
							["sizeOverride"] = 22,
							["desaturate"] = true,
							["maxDuration"] = 0,
							["enable"] = false,
							["priority"] = "Blacklist,Boss,Personal,RaidDebuffs,CastByUnit,Whitelist",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = -3,
						},
						["pvpTrinket"] = {
							["size"] = 44,
						},
						["power"] = {
							["text_format"] = "",
							["height"] = 6,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 2,
								["text_format"] = "[name:veryshort]",
								["yOffset"] = 8,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitPower"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = -2,
								["text_format"] = "[power:current]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "RIGHT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitHealth"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 2,
								["text_format"] = "[health:percent]",
								["yOffset"] = -8,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "LEFT",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
						},
						["healPrediction"] = {
							["enable"] = false,
						},
						["colorOverride"] = "FORCE_ON",
						["growthDirection"] = "UP",
						["name"] = {
							["text_format"] = "",
						},
						["spacing"] = 3,
						["height"] = 46,
						["buffs"] = {
							["countFontSize"] = 13,
							["sizeOverride"] = 22,
							["maxDuration"] = 0,
							["enable"] = false,
							["priority"] = "Blacklist,CastByUnit,Dispellable,Whitelist,RaidBuffsElvUI",
							["countFont"] = "SFUIDisplayCondensed-Semibold",
							["yOffset"] = 20,
						},
						["health"] = {
							["frequentUpdates"] = true,
							["text_format"] = "",
						},
						["width"] = 180,
					},
					["pettarget"] = {
						["colorOverride"] = "FORCE_ON",
						["health"] = {
							["frequentUpdates"] = true,
						},
					},
					["pet"] = {
						["debuffs"] = {
							["attachTo"] = "BUFFS",
							["priority"] = "Blacklist,Personal,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist",
						},
						["threatStyle"] = "NONE",
						["castbar"] = {
							["enable"] = false,
							["height"] = 20,
							["width"] = 200,
						},
						["customTexts"] = {
							["UnitName"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[name:abbrev:short]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = false,
								["size"] = 14,
							},
							["UnitPower"] = {
								["attachTextTo"] = "Power",
								["xOffset"] = 0,
								["text_format"] = "[power:current]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
							["UnitHealth"] = {
								["attachTextTo"] = "Health",
								["xOffset"] = 0,
								["text_format"] = "[health:current] - [health:max]",
								["yOffset"] = 0,
								["font"] = "SFUIDisplayCondensed-Semibold",
								["justifyH"] = "CENTER",
								["fontOutline"] = "OUTLINE",
								["enable"] = true,
								["size"] = 14,
							},
						},
						["healPrediction"] = {
							["enable"] = false,
						},
						["colorOverride"] = "FORCE_ON",
						["width"] = 120,
						["name"] = {
							["text_format"] = "",
						},
						["fader"] = {
							["enable"] = false,
						},
						["height"] = 44,
						["buffs"] = {
							["priority"] = "Blacklist,Personal,PlayerBuffs,Dispellable",
						},
						["health"] = {
							["frequentUpdates"] = true,
						},
						["power"] = {
							["attachTextTo"] = "Frame",
							["xOffset"] = 0,
							["height"] = 6,
						},
					},
				},
			},
			["bags"] = {
				["countFontSize"] = 14,
				["itemLevelFont"] = "SFUIDisplayCondensed-Semibold",
				["split"] = {
					["bagSpacing"] = 2,
				},
				["itemLevelxOffset"] = 1,
				["itemInfoFontOutline"] = "OUTLINE",
				["itemInfoFontSize"] = 14,
				["bagSize"] = 38,
				["itemLevelyOffset"] = 1,
				["countxOffset"] = 1,
				["bagWidth"] = 450,
				["moneyCoins"] = false,
				["countyOffset"] = 1,
				["bagButtonSpacing"] = 0,
				["bagBar"] = {
					["justBackpack"] = true,
					["spacing"] = -1,
					["size"] = 40,
					["mouseover"] = true,
					["growthDirection"] = "HORIZONTAL",
				},
				["countFontOutline"] = "OUTLINE",
				["bankSize"] = 38,
				["moneyFormat"] = "CONDENSED",
				["bankWidth"] = 396,
				["itemLevelFontOutline"] = "OUTLINE",
				["clearSearchOnClose"] = true,
				["countFont"] = "SFUIDisplayCondensed-Semibold",
				["itemLevelFontSize"] = 14,
				["itemInfoFont"] = "SFUIDisplayCondensed-Semibold",
			},
			["auras"] = {
				["debuffs"] = {
					["countFontSize"] = 14,
					["durationFontSize"] = 14,
					["size"] = 34,
					["horizontalSpacing"] = 3,
					["wrapAfter"] = 13,
				},
				["fontOutline"] = "OUTLINE",
				["buffs"] = {
					["countFontSize"] = 14,
					["durationFontSize"] = 14,
					["size"] = 34,
					["verticalSpacing"] = 20,
					["horizontalSpacing"] = 3,
					["wrapAfter"] = 13,
				},
				["cooldown"] = {
					["override"] = true,
					["hhmmColor"] = {
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["mmssColor"] = {
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["secondsColor"] = {
						["b"] = 0,
					},
					["mmssThreshold"] = 600,
					["checkSeconds"] = true,
				},
				["font"] = "SFUIDisplayCondensed-Semibold",
			},
		}
