-- KyaUI: perfil de Skada (extraido de Kyarox, 'MerfinUI v(Normal)7.05'). Generado automaticamente.
local addonName, addonTable = ...
KyaUI = KyaUI or {}
KyaUI.SkadaData = {
			["scroll"] = {
				["speed"] = 2,
				["icon"] = true,
				["button"] = "MiddleButton",
			},
			["namedisplay"] = 1,
			["modules"] = {
				["deathlogevents"] = 15,
				["threat"] = {
					["soundfile"] = "Fel Nova",
					["flash"] = true,
					["message"] = false,
					["notankwarnings"] = true,
					["output"] = 1,
					["shake"] = false,
					["threshold"] = 90,
					["sound"] = false,
					["frequency"] = 2,
				},
				["failschannel"] = "AUTO",
				["deathannounce"] = false,
				["deathchannel"] = "AUTO",
				["interruptchannel"] = "SAY",
				["parrychannel"] = "AUTO",
				["deathlogthreshold"] = 2000,
			},
			["prepotion"] = true,
			["windows"] = {
				{
					["barheight"] = 21,
					["barslocked"] = true,
					["modeincombat"] = "Damage",
					["numfont"] = "SFUIDisplayCondensed-Semibold",
					["combattimer"] = false,
					["hidden"] = false,
					["y"] = -392,
					["barfont"] = "SFUIDisplayCondensed-Semibold",
					["title"] = {
						["toolbaropacity"] = 0.9,
						["textcolor"] = {
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["color"] = {
							["a"] = 0.7100000083446503,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["font"] = "SFUIDisplayCondensed-Semibold",
						["borderthickness"] = 0,
						["height"] = 19,
						["texture"] = "Flatt",
					},
					["x"] = 840,
					["point"] = "BOTTOMRIGHT",
					["showself"] = true,
					["barcolor"] = {
						["a"] = 0.85,
					},
					["mode"] = "Damage",
					["childmode"] = 0,
					["spark"] = false,
					["bartexture"] = "Flatt",
					["barwidth"] = 230,
					["barspacing"] = 1,
					["smoothing"] = true,
					["enablebackground"] = true,
					["sticky"] = false,
					["background"] = {
						["color"] = {
							["a"] = 0.5,
						},
						["height"] = 239,
					},
					["name"] = "Main",
				}, -- [1]
				{
					["titleset"] = true,
					["barheight"] = 21,
					["color"] = {
						["a"] = 0.6,
						["b"] = 0.3,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["classicons"] = true,
					["barslocked"] = true,
					["useframe"] = true,
					["enabletitle"] = true,
					["wipemode"] = "",
					["numfont"] = "SFUIDisplayCondensed-Semibold",
					["set"] = "current",
					["child"] = "",
					["hidden"] = false,
					["clamped"] = true,
					["y"] = -195,
					["barfont"] = "SFUIDisplayCondensed-Semibold",
					["name"] = "Healing",
					["x"] = 840,
					["display"] = "bar",
					["showself"] = true,
					["barfontflags"] = "",
					["isusingelvuiskin"] = true,
					["numfontflags"] = "",
					["strata"] = "LOW",
					["classcolortext"] = false,
					["spellschoolcolors"] = true,
					["barbgcolor"] = {
						["a"] = 0.6,
						["b"] = 0.3,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["barcolor"] = {
						["a"] = 0.85,
						["b"] = 0.8,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["numfontsize"] = 13,
					["barfontsize"] = 13,
					["tooltippos"] = "NONE",
					["hideauto"] = 1,
					["title"] = {
						["textcolor"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["color"] = {
							["a"] = 0.7100000083446503,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["bordertexture"] = "None",
						["toolbar"] = 1,
						["height"] = 19,
						["borderinsets"] = 0,
						["font"] = "SFUIDisplayCondensed-Semibold",
						["borderthickness"] = 0,
						["spacing"] = 1,
						["fontflags"] = "",
						["fontsize"] = 13,
						["bordercolor"] = {
							["a"] = 1,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["texture"] = "Flatt",
					},
					["height"] = 30,
					["barorientation"] = 1,
					["mode"] = "Absorbs and Healing",
					["buttons"] = {
						["segment"] = true,
						["menu"] = true,
						["mode"] = true,
						["report"] = true,
						["reset"] = true,
					},
					["width"] = 600,
					["specicons"] = true,
					["textcolor"] = {
						["b"] = 0.9,
						["g"] = 0.9,
						["r"] = 0.9,
					},
					["spark"] = false,
					["bartexture"] = "Flatt",
					["barwidth"] = 230,
					["barspacing"] = 1,
					["enablebackground"] = true,
					["smoothing"] = true,
					["baroffset"] = 0,
					["modeincombat"] = "Absorbs and Healing",
					["scale"] = 1,
					["classcolorbars"] = true,
					["isusingclasscolors"] = true,
					["sticky"] = false,
					["background"] = {
						["tile"] = false,
						["color"] = {
							["a"] = 0.5,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["bordercolor"] = {
							["a"] = 0.5,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["borderinsets"] = 0,
						["borderthickness"] = 1,
						["height"] = 150,
						["bordertexture"] = "None",
						["tilesize"] = 0,
						["texture"] = "Solid",
					},
					["combattimer"] = false,
				}, -- [2]
			},
			["fofrostmourne"] = true,
			["report"] = {
				["channel"] = "party",
				["mode"] = "Absorbs and Healing",
			},
			["combatlogfix"] = true,
			["combatlogfixtime"] = 2,
			["smartwait"] = 5,
			["smartstop"] = false,
			["firsthit"] = false,
			["inCombat"] = false,
			["spamage"] = false,
			["modulesBlocked"] = {
				["Debuffs"] = false,
				["Activity"] = false,
				["Sunder Counter"] = true,
				["CC Taken"] = false,
				["Absorbs"] = false,
				["CC Done"] = false,
				["Useful Damage"] = false,
				["Resources"] = true,
				["CC Breakers"] = true,
				["Potions"] = false,
				["Overkill"] = false,
				["Friendly Fire"] = false,
				["Damage Taken By Spell"] = true,
				["Absorbs and Healing"] = false,
				["Interrupts"] = false,
			},
			["columns"] = {
				["Skada_Absorbs_Percent"] = false,
				["Skada_Dispels_sPercent"] = false,
				["Activity_Percent"] = true,
				["Absorbs_Percent"] = false,
				["Death log_Change"] = true,
				["Skada_Absorbs and Healing_Percent"] = false,
				["Skada_Damage_Percent"] = false,
				["Skada_Damage_Comparison_Percent"] = false,
				["Damage_Percent"] = false,
				["Skada_Healing_Percent"] = false,
				["Skada_DPS_Percent"] = false,
				["Skada_Damage_Comparison_DPS"] = true,
				["Absorbs and healing_Percent"] = false,
				["Skada_Enemy Damage Done_Percent"] = false,
				["Death log_Health"] = false,
				["Skada_Damage Taken_Percent"] = false,
				["Skada_Enemy Damage Taken_Percent"] = false,
				["Death log_Percent"] = false,
				["Skada_Deaths_Death log_Percent"] = false,
				["Skada_Threat_Percent"] = true,
				["Skada_Buffs_Percent"] = false,
			},
			["updatefrequency"] = 1.5,
			["absdamage"] = true,
			["moduleicons"] = true,
			["onlykeepbosses"] = true,
}
